apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.elastic.co
      chart: elasticsearch
      targetRevision: 8.5.1
      helm:
        valueFiles:
          - $values/helm-charts/elasticsearch/values.yaml
          - $values/environments/dev/elasticsearch-values.yaml
    - repoURL: https://github.com/la-belle-femme/ticket-269-team-wariors-deploying-and-optimizing-kibana-chart-with-ArgoCD.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: elk-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
