apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/la-belle-femme/ticket-269-team-wariors-deploying-and-optimizing-kibana-chart-with-ArgoCD.git
    targetRevision: HEAD
    path: helm-charts/kibana-custom
    helm:
      valueFiles:
        - values.yaml
        - ../../environments/dev/kibana-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: elk-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
