# Kibana Helm Chart Values for Development
replicas: 1

# Resource allocation
resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

# Elasticsearch connection (HTTP, not HTTPS)
elasticsearchHosts: "http://elasticsearch-dev-master:9200"

# Service configuration
service:
  type: NodePort
  port: 5601
  nodePort: 30561

# Health checks
healthCheckPath: "/app/kibana"

# Kibana configuration
kibanaConfig:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.shutdownTimeout: "5s"
    elasticsearch.hosts: ["http://elasticsearch-dev-master:9200"]
    monitoring.ui.container.elasticsearch.enabled: true
    # Disable security features to match Elasticsearch
    elasticsearch.ssl.verificationMode: none
    elasticsearch.username: ""
    elasticsearch.password: ""

# Image configuration
image: "docker.elastic.co/kibana/kibana"
imageTag: "8.5.1"
imagePullPolicy: "IfNotPresent"

# Protocol
protocol: http

# Ingress disabled for development
ingress:
  enabled: false

# Resource policy
podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000

# Disable security-related features
elasticsearchCredentialSecret: ""

# Disable the problematic pre-install hooks
extraInitContainers: []

# Environment variables to disable security
extraEnvs:
  - name: ELASTICSEARCH_USERNAME
    value: ""
  - name: ELASTICSEARCH_PASSWORD
    value: ""
  - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
    value: "none"
