image:
  repository: docker.elastic.co/kibana/kibana
  tag: 8.5.1
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort
  port: 5601
  nodePort: 30561

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

elasticsearch:
  hosts: "http://elasticsearch-dev-master:9200"

nameOverride: "kibana-dev"
