# Elasticsearch Helm Chart Values for Development
clusterName: "elasticsearch"
nodeGroup: "master"

# Single node setup
replicas: 1
minimumMasterNodes: 1

# Adequate resources for proper functioning
resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "3Gi"

# Storage configuration
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 10Gi

# Security disabled for development
esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false
    xpack.security.enrollment.enabled: false
    xpack.security.http.ssl.enabled: false
    xpack.security.transport.ssl.enabled: false

# Service configuration  
service:
  type: ClusterIP
  httpPort: 9200
  transportPort: 9300

# Environment variables
extraEnvs:
  - name: discovery.type
    value: single-node
  - name: ES_JAVA_OPTS
    value: "-Xmx1g -Xms1g"

# Image configuration
image: "docker.elastic.co/elasticsearch/elasticsearch"
imageTag: "8.5.1"
imagePullPolicy: "IfNotPresent"

protocol: http
secretMounts: []

# Disable problematic features
createCert: false
secret:
  enabled: false
