# Elasticsearch Helm Chart Values - Single Node Development Setup
clusterName: "elasticsearch"
nodeGroup: "master"

# Single node configuration - THE CORRECT WAY
replicas: 1
minimumMasterNodes: 1

# CRITICAL: Use single node discovery - prevents cluster.initial_master_nodes
esMajorVersion: "8"
antiAffinity: "soft"

# Resource allocation for development
resources:
  requests:
    cpu: "300m"
    memory: "1Gi"
  limits:
    cpu: "500m"  
    memory: "1Gi"

# Storage configuration
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 5Gi

# DISABLE ALL SECURITY
createCert: false
secret:
  enabled: false

esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false
    xpack.security.enrollment.enabled: false
    xpack.security.http.ssl.enabled: false
    xpack.security.transport.ssl.enabled: false
    discovery.type: single-node

# Simple HTTP service
service:
  type: ClusterIP
  httpPort: 9200
  transportPort: 9300

# DISABLE READINESS PROBE - it's causing issues
readinessProbe:
  enabled: false

# Basic environment
extraEnvs:
  - name: ES_JAVA_OPTS
    value: "-Xmx512m -Xms512m"

# Image
image: "docker.elastic.co/elasticsearch/elasticsearch"
imageTag: "8.5.1"

# HTTP protocol only
protocol: http
secretMounts: []
