clusterName: "elasticsearch"
nodeGroup: "master"

replicas: 1
minimumMasterNodes: 1

# Generous resources for t3.2xlarge
resources:
  requests:
    cpu: "1000m"
    memory: "4Gi"
  limits:
    cpu: "2000m"
    memory: "6Gi"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 20Gi

# Security disabled
esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false
    xpack.security.enrollment.enabled: false
    xpack.security.http.ssl.enabled: false
    xpack.security.transport.ssl.enabled: false

service:
  type: ClusterIP
  httpPort: 9200
  transportPort: 9300

extraEnvs:
  - name: discovery.type
    value: single-node
  - name: ES_JAVA_OPTS
    value: "-Xmx3g -Xms3g"

image: "docker.elastic.co/elasticsearch/elasticsearch"
imageTag: "8.5.1"
protocol: http
createCert: false
secret:
  enabled: false
secretMounts: []
