# Development-specific overrides for custom Kibana chart
nameOverride: "kibana-dev"

# Lower resources for development
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi

# Dev Elasticsearch connection
elasticsearch:
  hosts: "http://elasticsearch-dev-master:9200"

# Service configuration for dev
service:
  type: NodePort
  port: 5601
  nodePort: 30561
